/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.fallenangelsofficialmod;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class FallenangelsofficialmodModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public FallenangelsofficialmodModElements() {
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "nevergonnagiveyouup"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "nevergonnagiveyouup")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "deja-vu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "deja-vu")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "drip-sus"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "drip-sus")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "earthbound-sanctuary-guardian"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "earthbound-sanctuary-guardian")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "giorno-russian"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "giorno-russian")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "himno-betis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "himno-betis")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "himno-espana"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "himno-espana")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "il-vento-doro"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "il-vento-doro")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "megalovania"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "megalovania")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "roller-disco"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "roller-disco")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "tarantella-napoletana"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "tarantella-napoletana")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "traditionell-musette"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "traditionell-musette")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "wormboss"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "wormboss")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "your-reality"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "your-reality")));
		sounds.put(new ResourceLocation("fallenangelsofficialmod", "alma-partia"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("fallenangelsofficialmod", "alma-partia")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("fallenangelsofficialmod").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == FallenangelsofficialmodModElements.ModElement.class)
						elements.add((FallenangelsofficialmodModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(FallenangelsofficialmodModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		FallenangelsofficialmodMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final FallenangelsofficialmodModElements elements;
		protected final int sortid;
		public ModElement(FallenangelsofficialmodModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
